const workflow = ["Confirm the blast radius", "Inspect pod events", "Scale the recovered deployment"];

export default function Home() {
  return <main className="mx-auto min-h-screen max-w-6xl px-6 py-10 md:px-10">
    <nav className="flex items-center justify-between"><strong className="text-xl tracking-tight">Context<span className="text-[#38e8a0]">SOP</span></strong><a className="rounded-lg border border-[#203249] px-4 py-2 text-sm" href="#demo">View the workflow</a></nav>
    <section className="grid gap-12 py-24 md:grid-cols-[1.05fr_.95fr] md:items-center">
      <div><p className="mb-4 text-sm font-semibold tracking-[.18em] text-[#38e8a0]">INCIDENT OPERATIONS, COMPILED</p><h1 className="m-0 text-5xl font-semibold leading-[1.02] tracking-tight md:text-7xl">Turn incident noise into <span className="text-[#9b7bff]">reliable action.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#93a6bd]">ContextSOP transforms operational transcripts into stateful, validated runbooks—so your team can move from diagnosis to recovery with confidence.</p><div className="mt-9 flex gap-3"><a className="rounded-lg bg-[#38e8a0] px-5 py-3 font-semibold text-[#07111f]" href="#demo">Explore the demo</a><a className="rounded-lg border border-[#203249] px-5 py-3 font-semibold" href="/dashboard">Open workspace</a></div></div>
      <div id="demo" className="rounded-2xl border border-[#203249] bg-[#0b1728]/90 p-5 shadow-2xl shadow-black/20"><div className="mb-4 flex items-center gap-2 text-xs text-[#93a6bd]"><span className="h-2 w-2 rounded-full bg-[#f6b74c]" /> RAW INCIDENT → WORKFLOW DSL</div><div className="grid gap-4 sm:grid-cols-2"><pre className="m-0 overflow-auto rounded-xl bg-[#050c16] p-4 text-xs leading-6 text-[#93a6bd]">{`10:41 pod payments-api restarting\n10:43 OOMKilled confirmed\n10:47 raise memory limit\n10:49 rollout healthy`}</pre><div className="rounded-xl border border-[#38e8a0]/30 bg-[#0b201f] p-4"><p className="mt-0 text-xs font-semibold text-[#38e8a0]">RECOVERY RUNBOOK · 3 STEPS</p>{workflow.map((step, index) => <div className="mb-3 flex gap-2 text-sm" key={step}><span className="grid h-5 w-5 place-items-center rounded-full border border-[#38e8a0] text-[10px] text-[#38e8a0]">{index + 1}</span>{step}</div>)}<code className="block rounded bg-black/30 p-2 text-[11px] text-[#d7ccff]">kubectl rollout status deploy/$&#123;SERVICE&#125;</code></div></div></div>
    </section>
    <section className="grid gap-4 pb-12 md:grid-cols-3">{[["Structured by design", "The UI renders a validated workflow DSL—not model-generated code."], ["Safe under pressure", "Commands are parameterized and copyable, never executed in the browser."], ["Built for teams", "Tenant isolation, audit history, and execution state are first-class." ]].map(([title, body]) => <article className="rounded-xl border border-[#203249] bg-[#0b1728]/70 p-5" key={title}><h2 className="mt-0 text-base">{title}</h2><p className="mb-0 text-sm leading-6 text-[#93a6bd]">{body}</p></article>)}</section>
  </main>;
}
